### ISSUE TITLE
macOS Monterey

### ISSUE THREAD

**Issue by liryan1** [sanderland/katrain#489] opened 2021-11-12 15:32 UTC
Hello,

I upgraded to macOS Monterey and the app stopped opening. It pops up but closes immediately. I am wondering if anyone else had the same issue? 

A successful reinstallation did not fix the problem.

Thanks!

**Comment by sanderland** [comment] 2021-11-12 16:19
Is this on the new M1 processors or otherwise?

**Comment by liryan1** [comment] 2021-11-13 14:32
My friend's computer, not M1 processors. 2017 15-inch Mac, 16G memory, 2.9GHz i7 processor

**Comment by sanderland** [comment] 2021-11-13 15:14
Have you tried running from pip / from source?

**Comment by yizhiyong** [comment] 2021-11-16 03:47
m1, mac mini,  after upgraded to macOS Monterey,  katrain cannot be opened..

**Comment by sanderland** [comment] 2021-11-19 08:31
This issue has been confirmed by kivy developers and one of them is investigating a fix.

**Comment by niubaoshu** [comment] 2021-11-22 07:46
> Is this on the new M1 processors or otherwise?

my computer is M1 processors ,also has this issue.

**Comment by MarcelGruenauer** [comment] 2021-11-25 19:12
macOS 12 seems to have done something to the Python installation. After trying many things, I found this way, which worked for me:

Use brew to install pyenv. Use pyenv to install Python 3.9.7. Compile and install kivy from the git repo. Install KaTrain using pip.

```
brew install pyenv cython
(new shell)
pyenv install 3.9.7
pyenv shell 3.9.7
pip3 install -U katrain
# install kivy from source
git clone git://github.com/kivy/kivy.git
cd kivy
python -m pip install -e ".[dev,full]"
```

**Comment by sanderland** [comment] 2021-11-25 19:21
Here are two recent .app's to try, wondering if either of them work. (Download the "artifact" at the bottom)

https://github.com/sanderland/katrain/actions/runs/1499396937

https://github.com/sanderland/katrain/actions/runs/1504976550

**Comment by sanderland** [comment] 2021-11-30 21:16
Work on improving kivy things for mac that will hopefully solve these issues: https://github.com/kivy/kivy-sdk-packager/issues/66

**Comment by hlstwizard** [comment] 2021-12-01 23:07
```
错误	07:03:19.259784+0800	Kivy	cannot open file at line 45340 of [d24547a13b]
错误	07:03:19.259805+0800	Kivy	os_unix.c:45340: (2) open(/var/db/DetachedSignatures) - No such file or directory
默认	07:03:19.260025+0800	Kivy	MacOS error: -67062
默认	07:03:19.262937+0800	Kivy	MacOS error: -67062
默认	07:03:19.264539+0800	Kivy	Cannot validate nib. Bundle is not codesigned: <private>, <private> <private>
```

I'd believe it is a Kivy issue rather than katrain one. Hoping it could get fixed soon.

**Comment by hlstwizard** [comment] 2021-12-02 03:40
> ```
> python -m pip install -e ".[dev,full]"
> ```

This works for me! Thanks @MarcelGruenauer !

I'd believe the key step is running kivy install from src rather than using the packed one.

**Comment by MarcelGruenauer** [comment] 2021-12-02 13:06
I also upgraded my Intel iMac to Monterey. Again KaTrain didn't work and I performed the steps out;ined above, but here it would only work if I did *not* install kivy from source and stopped at the `pip3 install -U katrain` step.

**Comment by sanderland** [comment] 2021-12-04 08:37
> ```
> 错误	07:03:19.259784+0800	Kivy	cannot open file at line 45340 of [d24547a13b]
> 错误	07:03:19.259805+0800	Kivy	os_unix.c:45340: (2) open(/var/db/DetachedSignatures) - No such file or directory
> 默认	07:03:19.260025+0800	Kivy	MacOS error: -67062
> 默认	07:03:19.262937+0800	Kivy	MacOS error: -67062
> 默认	07:03:19.264539+0800	Kivy	Cannot validate nib. Bundle is not codesigned: <private>, <private> <private>
> ```
> 
> I'd believe it is a Kivy issue rather than katrain one. Hoping it could get fixed soon.

@misl6 does this help?

**Comment by misl6** [comment] 2021-12-04 08:44
Needs some investigation.
I will DM you in a while, I have an alpha status release to test 😄

**Comment by sanderland** [comment] 2021-12-05 21:23
@MarcelGruenauer @liryan1 @hlstwizard it would help the upstream developer if one of you could test the app from this build:
https://github.com/misl6/katrain/actions/runs/1541755325

**Comment by bjeanes** [comment] 2021-12-05 23:23
I'm on Apple Silicon with Monterey (new MBPs) and that build did work for me! However, it crashes if opening it from within the disk image:

```
❯ /Volumes/KaTrain/KaTrain.app/Contents/MacOS/KaTrain
/Volumes/KaTrain/KaTrain.app/Contents/Resources/venv/bin /Volumes/KaTrain/KaTrain.app/Contents/Resources
 Traceback (most recent call last):
   File "/Volumes/KaTrain/KaTrain.app/Contents/Resources/yourapp", line 5, in <module>
     from katrain.__main__ import run_app
   File "/Volumes/KaTrain/KaTrain.app/Contents/Resources/venv/lib/python3.9/site-packages/katrain/__main__.py", line 9, in <module>
     import kivy
   File "/Volumes/KaTrain/KaTrain.app/Contents/Resources/venv/lib/python3.9/site-packages/kivy/__init__.py", line 340, in <module>
     mkdir(kivy_home_dir)
 OSError: [Errno 30] Read-only file system: '/Volumes/KaTrain/KaTrain.app/Contents/Resources/.kivy'
```

I'm not sure what it needs to write `.kivy` for but it seems like it should probably be `~/.kivy` or somewhere outside of the application package itself. 

In any case, moving it to ~/Applications and then opening did work!

**Comment by hlstwizard** [comment] 2021-12-06 03:13
> @MarcelGruenauer @liryan1 @hlstwizard it would help the kivy developer if one of you could test the app from this build: https://github.com/misl6/katrain/actions/runs/1541755325

Works for me on Intel Monterey!

**Comment by CRDE** [comment] 2021-12-06 07:24
> > build: https://github.com/misl6/katrain/actions/runs/1541755325
> 
> Works for me on Intel Monterey!

and for me it's now working on M1 and Monterey. Thank you all!

**Comment by misl6** [comment] 2021-12-08 08:03
Thanks to everyone for testing it! That helped a lot to speed up the development process.
@sanderland I will keep you updated about the upstream status.

**Comment by GoPlayers** [comment] 2022-01-30 10:34
I'm new in mac. I'm still not install katrain. App is crashing I think. Not give any error. Can you help me?

**Comment by sanderland** [comment] 2022-01-30 17:54
> I'm new in mac. I've still not install katrain. App is crashing I think. Not give any error. Can you help me?

Have you tried the builds linked in this thread?
https://github.com/misl6/katrain/actions/runs/1541755325

**Comment by sanderland** [comment] 2022-03-13 09:46
#489 reports zsh: /usr/local/bin/katrain: bad interpreter: /usr/local/opt/python/bin/python3.7: no such file or directory
on monterey with a fix to run from source

**Comment by realityfilter** [comment] 2022-03-21 16:38
The current builds available from actions menu are working on Monterey. But there are some issues:

- resizing the window does not change the python window inside
- closing the application throws error and is not successful

**Comment by sanderland** [comment] 2022-03-21 17:08
> The current builds available from actions menu are working on Monterey. But there are some issues:
> 
> * resizing the window does not change the python window inside
> * closing the application throws error and is not successful
Glad to hear it's mostly working. Perhaps file with https://github.com/kivy/kivy-sdk-packager/ for remaining bugs or ask @misl6

**Comment by realityfilter** [comment] 2022-03-28 21:12
The current OSX build is fine and fixes all issues. And the graphics is crispy. Thanks for the effort! When to expect a brew updated version?

**Comment by sanderland** [comment] 2022-03-29 11:00
> The current OSX build is fine and fixes all issues. And the graphics is crispy. Thanks for the effort! When to expect a brew updated version?

When a mac user who cares about this submits a PR to homebrew.

**Comment by realityfilter** [comment] 2022-03-31 11:53
I wanted to do a merge request. When testing the new version I was hitting the same bug as @bjeanes was describing. `Permission denied: '/Applications/KaTrain.app/Contents/Resources/.kivy'` I will wait until this is resolved, otherwise the new version will not start from Applications folder.

**Comment by grubhub0101** [comment] 2022-05-21 18:58
Issues persists with dmg installation 1.11 on Monterey MBP not M1 "ERROR: Engine died unexpectedly without sending output: status -6"
Can open, change settings. Looks like a great program with functionality, hope this gets resolved.

**Comment by realityfilter** [comment] 2022-07-02 15:29
The kivy sdk has now a fix for the permission problem: https://github.com/kivy/kivy-sdk-packager/issues/74

**Comment by sanderland** [comment] 2022-10-09 18:06
Closed among inactive issues as a general cleanup

**Closed by sanderland** 2022-10-09 18:06 UTC
