### ISSUE TITLE
Rotated WBaduk games

### ISSUE THREAD

**Issue by SylvainNZ** [sanderland/katrain#419] opened 2021-04-27 07:18 UTC
Nothing terrible but the .NGF files from WBaduk appear rotated by 180 degrees.
Not critical but its more "comfortable" to review in the same orientation that the game is played.

**Comment by sanderland** [comment] 2021-04-27 10:51
could you attach an example so i can test? does sabaki do it right?

**Comment by rooklift** [comment] 2021-04-27 10:58
Sabaki's code, although I think it's been changed a bit now, is ultimately derived from the same code...

https://github.com/SabakiHQ/Sabaki/pull/177

**Comment by sanderland** [comment] 2021-04-29 19:23
![image](https://user-images.githubusercontent.com/48946947/116606478-12de9200-a931-11eb-8746-8a70052222f6.png)

confirmed the same as sabaki,

**Comment by SylvainCME** [comment] 2021-04-30 01:12
yes, so I can confirm that some files are working and some are rotated 180 degrees, here are two examples:

[WorkingFile.zip](https://github.com/sanderland/katrain/files/6402480/WorkingFile.zip)
[RotatedFile.zip](https://github.com/sanderland/katrain/files/6402487/RotatedFile.zip)

I sent the NGFs and screenshots comparing Wbaduk/KaTrain interface

**Comment by SylvainNZ** [comment] 2021-04-30 01:15
Yes, I can confirm some files are working and some are rotated 180 degrees.
Here are 2 examples, I attached the NGFs and a screenshot showing the difference between WBaduk and KaTrain interfaces:

[RotatedFile.zip](https://github.com/sanderland/katrain/files/6402495/RotatedFile.zip) 

[WorkingFile.zip](https://github.com/sanderland/katrain/files/6402493/WorkingFile.zip)

**Comment by sanderland** [comment] 2021-04-30 08:11
is wbaduk just rotating the board for white? there is nothing in the files to indicate any rotation. Does wbaduk load it's own files and show such effects?

**Comment by rooklift** [comment] 2021-04-30 10:10
I suppose it checks the name of the logged in user, compares it to the white player in the game record, and rotates it 180 if they match?

**Comment by SylvainNZ** [comment] 2021-05-07 03:20
hey guys, I thought you were right after checking a few games, but then I found that one which wasn't rotated for white :/

![image](https://user-images.githubusercontent.com/25375326/117393021-2a6bdb00-af2e-11eb-838b-e4a6cf6145cc.png)

[202104131235ankaketarosup193945.zip](https://github.com/sanderland/katrain/files/6438802/202104131235ankaketarosup193945.zip)

would you like me to check let's say 20 gibos and mark those which are totated or not?

**Comment by sanderland** [comment] 2021-05-07 07:40
Could you investigate whether rotated games are rotated in wbaduk with a different account / whether they show up the same for the opponent?

**Comment by SylvainCME** [comment] 2021-05-07 08:11
yes, it may take a few days but will do

**Comment by SylvainNZ** [comment] 2021-05-07 08:12
yes, it may take a few days but will do

**Comment by sanderland** [comment] 2021-06-28 12:21
Closing this due to lack of updates / low priority

**Closed by sanderland** 2021-06-28 12:21 UTC
