### ISSUE TITLE
Feature request: Life and death solving

### ISSUE THREAD

**Issue by obwohl** [sanderland/katrain#226] opened 2020-10-29 14:01 UTC
First: What a great software!

It would be nice to have a companion for solving complicated life and death problems. I don't know it this is more a problem of Katrain or Katago but I think it would be huge to have it.

**Comment by simonguoxm** [comment] 2020-11-01 01:50
I already use Katrain to do Life and Death problem.

**Comment by obwohl** [comment] 2020-11-01 02:31
How do you do this?

**Comment by simonguoxm** [comment] 2020-11-01 02:38
usually I put that L&D problem on a 7x7 or 9x9 board. Then load this sgf in KaTrain.

**Comment by sanderland** [comment] 2020-11-02 20:18
What @simonguoxm said, otherwise duplicate of #216

**Closed by sanderland** 2020-11-02 20:18 UTC
