### ISSUE TITLE
Support for NGF files (WBaduk)

### ISSUE THREAD

**Issue by SylvainNZ** [sanderland/katrain#83] opened 2020-06-20 01:45 UTC
That would be really nice to support Gibo (.gib) files so that we can import games from Tygem/WBaduk.

I imagine you would be able to convert it into SGF in the background using such script:
https://github.com/fohristiwhirl/xyz2sgf

And I don't think other programs have this feature yet!

**Comment by sanderland** [comment] 2020-06-20 09:09
I'd be happy to hook this up in the gui if someone extends sgf_parser.py. I know sabaki converts these files, so it's not a priority for me to support them.
@fohristiwhirl is the xyz2sgf code open-source / MIT?

**Comment by fohristiwhirl** [comment] 2020-06-20 10:27
Uh, sure, I give the KaTrain authors permission to copy, adapt, modify, and redistribute any of my code from xyz2sgf under any or no license.

You can also borrow code from here:

https://github.com/fohristiwhirl/gofish/blob/master/gofish/gib.py

**Comment by sanderland** [comment] 2020-06-20 12:19
> 
> 
> Uh, sure, I give the KaTrain authors permission to copy, adapt, modify, and redistribute any of the code from xyz2sgf under any or no license.
> 
> You can also borrow code from here (though if I recall rightly it's much the same):
> 
> https://github.com/fohristiwhirl/gofish/blob/master/gofish/gib.py
> 
> You might also find this page helpful:
> 
> https://senseis.xmp.net/?GIB
> 
> (By the way, Sabaki's GIB parser was [very much based](https://github.com/SabakiHQ/Sabaki/pull/177) on this, as well.)

Great, that looks like it's nicely self-contained! Thanks. :)

**Comment by sanderland** [comment] 2020-06-28 12:11
Implemented in 1.3, not sure about handicap placement and a few example gibo files with 2, 3, 6, 7, 8 stones would help here.

**Comment by fohristiwhirl** [comment] 2020-06-28 12:16
H3 is the only troublesome one - it should leave an empty star point in the bottom right.

**Comment by fohristiwhirl** [comment] 2020-06-28 12:36
By the way, just to check, does your internal coordinate system have 0,0 in the bottom left or top left?

**Comment by sanderland** [comment] 2020-06-28 12:40
My internal coords are 0,0 at the bottom left like GTP, so I changed the y coord to be 18-y

bottom right empty is confirmed correct, I basically only did this for handicaps
```
        if tygem:
            stones[2], stones[3] = stones[3], stones[2]
```

**Comment by SylvainNZ** [comment] 2020-07-07 23:29
Thank you for including this so quickly, much appreciated! I already used it today.

**Comment by SylvainNZ** [comment] 2020-07-07 23:36
@sanderland 
Now I just realised that for Wbaduk, even though they call it Gibo, it is a .ngf extension and the content of the file is different from a .gib. 

I found another python script from @fohristiwhirl which can read an ngf
https://github.com/fohristiwhirl/gofish/blob/master/gofish/ngf.py

Would you be keen to consider this as well if @fohristiwhirl is ok? 

Thank you

**Comment by fohristiwhirl** [comment] 2020-07-08 01:41
Uh sure, go ahead. NGF's a pretty weird file format. Some examples at: https://github.com/SabakiHQ/Sabaki/tree/master/test/ngf

My parser was pretty basic, though, I'm can't really speak to its correctness or completeness.

**Comment by sanderland** [comment] 2020-07-08 08:03
We'll see, but it'll be low priority since I've never used wbaduk myself. If someone wants to try their hand at this, sgf_parser.py is the file to look at.

**Comment by sanderland** [comment] 2020-07-08 17:38
will be released with 1.3.1

**Closed by sanderland** 2020-07-08 17:38 UTC
Labels: 1.3, enhancement, fixed

**Comment by SylvainNZ** [comment] 2020-07-09 09:12
Damn, so quick !

Thanks a lot !

**Comment by SylvainNZ** [comment] 2020-07-09 09:23
Sorry, that is me again @sanderland 

I think the file browser cannot show the ngf extension.
![image](https://user-images.githubusercontent.com/25375326/87022183-3c0b2600-c22a-11ea-872b-56ca7c6d10fe.png)
(its 1.3.1 and on the screenshot you can see that there are ngf files in this folder)

**Comment by sanderland** [comment] 2020-07-09 09:26
probably it's a lowercase/uppercase issue.

**Comment by SylvainNZ** [comment] 2020-07-09 09:29
I tried but without success (I restarted Katrain just in case)

**Comment by sanderland** [comment] 2020-07-09 09:34
You tried what? renaming NGF to ngf ?
What happens when you drag and drop a file onto katrain?

**Comment by SylvainNZ** [comment] 2020-07-09 09:41
yes, renaming to ngf didn't work.

I just realised the drag n drop works ! :) 
When I first tried I was on the file browser screen so I thought it didn't work.

**Comment by sanderland** [comment] 2020-07-09 09:49
That's strange, I can see both NGF and ngf fine
![image](https://user-images.githubusercontent.com/48946947/87025118-456ca200-c1da-11ea-9a07-582abd89f9ea.png)

**Comment by SylvainNZ** [comment] 2020-07-10 02:33
Wow that's strange indeed.

I made a folder with just 2 files with simple names but that didn't work.
![image](https://user-images.githubusercontent.com/25375326/87109658-5cce8c80-c2b9-11ea-8ca4-320a7527b966.png)

When I put an ngf alongside a gib and sgf, only the ngf doesn't show up.
Maybe we have slightly different versions.

**Comment by sanderland** [comment] 2020-07-10 15:19
Not sure what happened, maybe some caching in building the exe. Reuploaded them on the release page.

**Comment by SylvainNZ** [comment] 2020-07-12 07:38
Thank you, that did the trick
