### ISSUE TITLE
Fox SGF Issue

### ISSUE THREAD

**Issue by Giannechini** [sanderland/katrain#150] opened 2020-07-26 18:59 UTC
[Fox sgf examples.zip](https://github.com/sanderland/katrain/files/4978214/Fox.sgf.examples.zip)

About half of the games that I play on Fox I can't review using KaTrain. It looks like KaTrain reserves a spot for the 0th move, but some of the Fox games will place a stone on the 0th move, instead of the first. I've attached a couple images to better illustrate my point. Also, I can analyze these games using Lizzie still. KaTrain works well with all of the OGS games that I've reviewed. Really enjoying using KaTrain for analysis. Can't upload sgf's so I zipped one sgf that works and one that doesn't. I also added a couple links to the same games, although downloading from the link looks a lot different than downloading from fox.

Link to Fox SGF where analyzing w/ KaTrain produces an error: http://h5.foxwq.com/txwqshare/index.html?chessid=1595196260010001191&boardsize=19&title=%E8%85%BE%E8%AE%AF%E9%87%8E%E7%8B%90%E5%9B%B4%E6%A3%8B%20-%20%E7%BD%91%E6%A3%8B%E6%A3%8B%E8%B0%B1&sourcetype=pc
[Fox sgf examples.zip](https://github.com/sanderland/katrain/files/4978211/Fox.sgf.examples.zip)

Link to Fox SGF where analyzing w/ KaTrain works: http://h5.foxwq.com/txwqshare/index.html?chessid=1595689716010001878&boardsize=19&title=%E8%85%BE%E8%AE%AF%E9%87%8E%E7%8B%90%E5%9B%B4%E6%A3%8B%20-%20%E7%BD%91%E6%A3%8B%E6%A3%8B%E8%B0%B1&sourcetype=pc

**Comment by sanderland** [comment] 2020-07-26 19:57
The problem is this `KM[0]HA[1]` , which is invalid in the SGF format anyway, and caused katrain to place 1 handicap stone -- the behaviour for placing handicap stones without an AB instruction is rather ill defined as this shouldn't normally happen.
It seems this is fox's bizarrely wrong way of communicating komi differences.
The bug is fixed in f13d5bb

**Closed** 2020-07-28 09:16 UTC

**Comment by Giannechini** [comment] 2020-08-03 16:22
Awesome, thanks!
