### ISSUE TITLE
Can KaTrain update automatically like Sabaki? And add 'Rated Game' like Zen7?

### ISSUE THREAD

**Issue by HackYardo** [sanderland/katrain#204] opened 2020-09-20 02:17 UTC
I can browse the web, delete old version files on my disk and download new version files from the web, but could KaTrain add a option to do these work?
I see 'Rank Estimate' is gone, however, I like 'Rated Game' in Zen7 very much! How to realize 'Rated Game' in KataGo? Maybe we can simply adjust the number of playouts/visits and use 6/10/15 block model to change the power of KaTaGo!

**Comment by sanderland** [comment] 2020-09-20 09:07
> I can browse the web, delete old version files on my disk and download new version files from the web, but could KaTrain add a option to do these work?

No

> I see 'Rank Estimate' is gone, however, I like 'Rated Game' in Zen7 very much! How to realize 'Rated Game' in KataGo? Maybe we can simply adjust the number of playouts/visits and use 6/10/15 block model to change the power of KaTaGo!

Did you check the large number of AI options present and their strength settings? Calibrated rank and scoreloss are most balanced.

**Comment by HackYardo** [comment] 2020-09-21 00:06
> 
> 
> > I see 'Rank Estimate' is gone, however, I like 'Rated Game' in Zen7 very much! How to realize 'Rated Game' in KataGo? Maybe we can simply adjust the number of playouts/visits and use 6/10/15 block model to change the power of KaTaGo!
> 
> Did you check the large number of AI options present and their strength settings? Calibrated rank and scoreloss are most balanced.

I did see these AI options, but KaTrain has no rating points!

**Comment by sanderland** [comment] 2020-09-21 07:23
Duplicate of #175

**Closed by sanderland** 2020-09-21 07:23 UTC
