### ISSUE TITLE
Don't start analysis again if a game contains analysis data already

### ISSUE THREAD

**Issue by Zaoliang** [sanderland/katrain#312] opened 2021-01-05 21:08 UTC
At moment Katrain starts analysis after a game has been loaded. 
This keeps user waiting a while,  depending on games progress or moves. 
 
I would like see the analysis data can be used directly and analysis just start from last move or new move.

If it is needed for a re-analysis of a game for some reason, then please don't make this as default.

**Comment by Azirine** [comment] 2021-01-06 05:49
I agree. Currently there is no way to access saved analysis data when loading a previously analysed game. All that is shown is the data from the re-analysis.

**Comment by sanderland** [comment] 2021-01-06 08:26
If you have the 'save analysis in sgf' box tixed in 1.7 it should save it.
Other than that, having 'fast visits' low, even at 1, makes fast loading near instant.

**Comment by Zaoliang** [comment] 2021-01-06 10:17
@sanderland  'save analysis in sgf' ? I use vsion 1.7 already. I checked menu and analysis but I cannot find this option.
Thanks!

**Comment by sanderland** [comment] 2021-01-06 10:19
![Uploading image.png…]()

**Comment by sanderland** [comment] 2021-01-06 10:19
![image](https://user-images.githubusercontent.com/48946947/103757384-fed4f480-5010-11eb-9acb-14973789082d.png)

**Comment by Zaoliang** [comment] 2021-01-06 10:34
@sanderland I tired this Cache analysis in SGF. No changes than before.  Low the value to 1 for 'Show stats if mocre than..visits' doesn't help in my case.

**Comment by sanderland** [comment] 2021-01-06 10:42
What did you try? Save a game with analysis and then load it?

**Comment by Zaoliang** [comment] 2021-01-06 11:00
@sanderland Yes, I saved changes with anaylsis and then reload my game. 
I tried now with low visits value in General/Engine settings, but this has no effect on behavior of analysis.


![katrain visits setting](https://user-images.githubusercontent.com/4113246/103761322-c3d5bf80-5016-11eb-9917-5fcc4bbcd217.jpg)

**Comment by sanderland** [comment] 2021-01-06 11:03
@Zaoliang what exactly are you doing?
* new game, play
* save
* load the resulting sgf
should load analysis

* load downloaded sgf
* analyze
* save
* load
has a bug which is fixed in 1.7.1

max visits should affect how much analysis is done. (fast visits if drag+drop or ticking 'fast' in load should be very quick with 10 visits!)

**Comment by Zaoliang** [comment] 2021-01-06 11:07
@sanderland load downloaded sgf, I see the difference. Thanks for your explanation!

**Comment by Azirine** [comment] 2021-01-06 11:09
I'm having this issue, even with "Cache analysis in SGF".

What I'm doing is:
1. Load SGF file
2. Wait for analysis
3. Save SGF with analysis
4. Close Katrain
5. Reopen Katrain
6. Load SGF with analysis

What I get is a new analysis, and all the analysis I've made before is not accessible.

**Comment by Zaoliang** [comment] 2021-01-06 11:13
@Azirine So I can reduce waiting time with load option 'Use fast analysis' :)

**Comment by Azirine** [comment] 2021-01-06 11:15
> @Azirine So I can reduce waiting time with load option 'Use fast analysis' :)

The problem is not the waiting time. When I set fast analysis with 1 visit, all that is shown is the analysis with 1 visit, even though I've done thousands of visits on every move before and saved it.

**Comment by sanderland** [comment] 2021-01-06 11:16
@Azirine yes that's a bug that will is fixed in the next version. You can kind of work around it with 'save as', I think. Otherwise it forgets to save the analysis format version, and on loading it's like "wrong version, ignore!"

**Comment by sanderland** [comment] 2021-01-16 18:14
fix released

**Closed by sanderland** 2021-01-16 18:14 UTC
