### ISSUE TITLE
Alt-tab changes mode

### ISSUE THREAD

**Issue by pdeblanc** [sanderland/katrain#313] opened 2021-01-05 23:54 UTC
On Ubuntu I use alt-tab to switch between applications. When I use alt-tab to switch to KaTrain from a different application, the tab keypress also causes KaTrain to toggle between Play and Analysis modes. The preferred behavior would be for KaTrain to remain in whatever mode it is currently in.

**Comment by sanderland** [comment] 2021-01-06 08:23
duplicate of #296

**Closed by sanderland** 2021-01-06 08:23 UTC
